#version 450
#extension GL_GOOGLE_include_directive : require
#include "src/shared/particles.inl"

layout(push_constant, scalar) uniform pc {ParticlesPC data;};

layout(local_size_x = PARTICLES_X_TILE_SIZE, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;  

    data.particles_out[index].position = data.particles_in[index].position + gl_GlobalInvocationID;
}